[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.120"
core = { path = "../core" }
log = "0.4.22"
env_logger = "0.11.5"
