[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
core = { path = "../core" }
log = "0.4.22"
env_logger = "0.11.3"
serde = { version = "1.0.203", features = ["derive"] }